# Configuration file for the Sphinx documentation builder.
#
# This build documents the source tree it is checked out alongside: the API
# reference is generated by sphinx-autoapi from ../flystar by static analysis,
# so the package does NOT need to be importable (and its runtime dependencies
# do not need to be installed) for the docs to build.

import os
import sys
import datetime
from configparser import ConfigParser

# -- Project information ------------------------------------------------------

conf = ConfigParser()
conf.read([os.path.join(os.path.dirname(__file__), '..', 'setup.cfg')])
setup_cfg = dict(conf.items('metadata'))

project = setup_cfg['name']
author = setup_cfg['author']
copyright = '{0}, {1}'.format(datetime.datetime.now().year, author)

# The package is deliberately not imported (see above), so take the version from
# installed metadata when it happens to be available and fall back to whatever
# Read the Docs is building otherwise.
try:
    from importlib.metadata import version as _get_version
    release = _get_version(project)
except Exception:
    release = os.environ.get('READTHEDOCS_VERSION', 'dev')
version = release.split('+')[0]

# -- General configuration ----------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'autoapi.extension',
    'myst_nb',
]

exclude_patterns = [
    '_build',
    '**.ipynb_checkpoints',
    'Thumbs.db',
    '.DS_Store',
]

highlight_language = 'python3'
nitpicky = False

# -- Napoleon (numpydoc-style docstrings) -------------------------------------

napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_use_param = True
napoleon_use_rtype = True

# This codebase's docstrings use several non-standard section headings. Map each
# onto the standard section it actually means, so napoleon renders them as real
# parameter/return lists instead of leaving them as stray RST section titles.
napoleon_custom_sections = [
    ('Required Parameters', 'Parameters'),
    ('Optional Parameters', 'Parameters'),
    ('Optional Inputs', 'Parameters'),
    ('Optional Input', 'Parameters'),
    ('Optional Keywords', 'Parameters'),
    ('Required table columns (input as keywords)', 'Parameters'),
    ('Optional table columns (input as keywords)', 'Parameters'),
    ('Optional table meta data', 'Parameters'),
    ('Output', 'Returns'),
]

# -- sphinx-autoapi -----------------------------------------------------------
#
# autoapi walks the source statically, so every module on this branch is picked
# up automatically -- including ones that post-date the old hand-maintained
# automodapi list (motion_model, parallax, startables ...).

autoapi_dirs = ['../flystar']
autoapi_root = 'api'
autoapi_type = 'python'
autoapi_member_order = 'groupwise'
autoapi_options = [
    'members',
    'undoc-members',
    'show-inheritance',
    'show-module-summary',
    'imported-members',
]
autoapi_ignore = [
    '*/conftest.py',
    '*/tests/*',
    '*/_astropy_init*',
    '*/version.py',
    '*/setup_package*',
    '*/conf.py',
    '*/parallax_cache/*',
    '*/extern/*',
    '*/data/*',
]
autoapi_add_toctree_entry = False   # the toctree entry lives in index.rst
autoapi_keep_files = False
autoapi_python_class_content = 'both'

# -- myst-nb (renders the example notebooks) ---------------------------------
#
# Notebooks are rendered from their stored outputs and are never executed at
# build time: executing them would require the full science stack plus the data
# files each example reads.

nb_execution_mode = 'off'
myst_heading_anchors = 4
myst_enable_extensions = ['dollarmath', 'amsmath', 'colon_fence']
suppress_warnings = ['mystnb.unknown_mime_type']

# -- Intersphinx --------------------------------------------------------------

intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'scipy': ('https://docs.scipy.org/doc/scipy/', None),
    'astropy': ('https://docs.astropy.org/en/stable/', None),
    'matplotlib': ('https://matplotlib.org/stable/', None),
}

# -- HTML output --------------------------------------------------------------

html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'navigation_depth': 3,
    'collapse_navigation': False,
}
html_static_path = ['_static']
templates_path = ['_templates']

github_project = setup_cfg.get('github_project', 'MovingUniverseLab/flystar')
html_context = {
    'display_github': True,
    'github_user': github_project.split('/')[0],
    'github_repo': github_project.split('/')[-1],
    'github_version': os.environ.get('READTHEDOCS_GIT_IDENTIFIER', 'main'),
    'conf_py_path': '/docs/',
}
